# Generated by Django 3.2.4 on 2021-06-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='subtitle',
        ),
    ]
